# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.variable }}.

title: Your Blog Name (e.g., Buriburiza3mon's Musings)
email: your-email@example.com (Optional, or remove)
description: >- # this means to ignore newlines until "baseurl:"
  Write a short description of your blog here.
baseurl: "" # the subpath of your site, e.g. /blog. For buriburiza3mon.github.io, this should be ""
url: "https://buriburiza3mon.github.io" # your site's domain
github_username: buriburiza3mon (Optional)

# Theme (Using a simplified approach here instead of gem-based for non-technical user)
# We will rely on GitHub Pages' default Jekyll build with custom layouts/includes

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Navigation links (you can add more)
nav_links:
  - title: Home
    url: /
  - title: About
    url: /about/
#  - title: Blog
#    url: /blog/ # If you want a dedicated blog listing page separate from homepage

# Footer content
footer_content: "© YYYY Your Name. Powered by Jekyll & GitHub Pages."

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be ignored by Jekyll.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
