title: buriburiza3mon
description: Blog | Writeups | About
theme: minima
lang: en
timezone: UTC
theme_mode: dark

url: "https://buriburiza3mon.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

custom_css:
  - /assets/css/custom.css
