baseURL = "https://buriburiza3mon.github.io/"
languageCode = "en-us"
title = "My InfoSec Research"
theme = "PaperMod"

[params]
    defaultTheme = "auto" # This gives you the automatic Light/Dark mode toggle
    ShowReadingTime = true
    ShowShareButtons = true
[outputs]
    home = ["HTML", "RSS", "JSON"] 

[[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 1
